language: node_js
node_js:
  - 0.11
  - 0.10
git:
  depth: 10
branches:
  only:
    - master
env:
  global:
  - secure: UqqgIm+c/2Btg0sQaX0yHsR5QhSOQa/CqV6AbznLKPfan6WQJEQWhxp371Zxie0D9o8g3TCjG71O3p8fk0acaJ2T7vAA4cGz54DsNT2SCNEzCBBGnPQX/vri623r7gv2FXJLAll548v+jLY206bx/WIKEMWTgaI8aX4oluca4zY=
  - secure: WKtGKEZlayIKZWucpsJ8zt+3ptkPO/2vld4As6ThrwVxvAu+4MP32dVJQOpPBDrPazWmy3SDdUJQ0LkqIoGK5G1Pu3ovTnriHwoH+JrY8YsrsOh0Z0XlPf1InnsYrUPfAOnPpxTotstY4xSXqX7qNXnjuo9I2IcmExAPpTgKrAA=
script: make test
before_script:
  - npm install -g bower
  - bower install
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - npm install karma-sauce-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  # Karma sauce is limited to running about 5-7 browsers (or it will timeout) at a time so we just run vendor by vendor here
  - karma start karma.conf-sauce.js --browsers FIREFOX_V4,FIREFOX_V11,FIREFOX_V21,FIREFOX_V30,FIREFOX_V35,CHROME_V26,CHROME_V31,CHROME_V39,CHROME_V40,ANDROID_V4.0,ANDROID_V4.3
  - karma start karma.conf-sauce.js --browsers IE_V7,IE_V8,IE_V9,IE_V10,IE_V11
  - karma start karma.conf-sauce.js --browsers SAFARI_V5,SAFARI_V6,SAFARI_V7,SAFARI_V8.0,OPERA_V11,OPERA_V12
notifications:
  email: false
